### ISSUE TITLE
Homepage discussion

### ISSUE THREAD

**Issue by 16yildiza** [Charles-T-King/website#37] opened 2015-04-15 18:33 UTC
Picture
Tagline
Testimonials/Success stories
About
Apply for a loan
Contact

**Comment by rvolyar** [comment] 2015-04-15 18:48
Here's a sample bootstrap landing page template that sort of fits the sections/layout we want.
http://ironsummitmedia.github.io/startbootstrap-landing-page/

**Comment by AbhinavMadahar** [comment] 2015-04-16 01:17
This is a duplicate of issue #5 so please put the discussion in there

**Closed by AbhinavMadahar** 2015-04-16 01:17 UTC
Labels: Duplicate
